{% set name = "intake-dataframe-catalog" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/intake_dataframe_catalog-{{ version }}.tar.gz
  sha256: 6ea2aef02504fd3b40b83728fceab9b4849f155e4eb7c0e181578c16fe3bb4c0

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.7
    - setuptools >=61.0.0
    - versioneer
    - pip
  run:
    - python >=3.7
    - intake
    - pandas

test:
  imports:
    - intake_dataframe_catalog
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ACCESS-NRI/intake-dataframe-catalog
  summary: An intake driver for a searchable table of intake sources and associated metadata
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - rxm7706
